spring:
  application:
    name: eureka.client.verb

server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  application:
    name: ${spring.application.name}
    description: This application returns a random verb based on the active profile
    version: '@project.version@'

---
spring:
  config:
    activate:
      on-profile: neutral-verb

words: accept(s),follow(s)

---
spring:
  config:
    activate:
      on-profile: positive-verb

words: love(s),like(s),adore(s)

---
spring:
  config:
    activate:
      on-profile: negative-verb

words: hate(s),detest(s)
